server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: internhub-backend

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 9
      minimum-idle: 5
      connection-timeout: 10000
      idle-timeout: 300000

  jackson:
    time-zone: UTC

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

jwt:
  signerkey: ${SIGNER_KEY}
  valid-duration: ${VALID_DURATION} # in HOURS
  refreshable-duration: ${REFRESHABLE_DURATION} # in HOURS

cors:
  allowed:
    origins: ${FRONTEND_URL}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
